// Code generated by protoc-gen-go.
// source: proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	proto

It has these top-level messages:
	Entity
	Request
	Response
	Message
*/
package internal

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Entity struct {
	Key              *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	StringValue      *string  `protobuf:"bytes,2,opt,name=string_value" json:"string_value,omitempty"`
	Int64Value       *int64   `protobuf:"varint,3,opt,name=int64_value" json:"int64_value,omitempty"`
	BoolValue        *bool    `protobuf:"varint,4,opt,name=bool_value" json:"bool_value,omitempty"`
	BytesValue       []byte   `protobuf:"bytes,5,opt,name=bytes_value" json:"bytes_value,omitempty"`
	StringList       []string `protobuf:"bytes,6,rep,name=string_list" json:"string_list,omitempty"`
	Int64List        []int64  `protobuf:"varint,7,rep,name=int64_list" json:"int64_list,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}

func (m *Entity) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Entity) GetStringValue() string {
	if m != nil && m.StringValue != nil {
		return *m.StringValue
	}
	return ""
}

func (m *Entity) GetInt64Value() int64 {
	if m != nil && m.Int64Value != nil {
		return *m.Int64Value
	}
	return 0
}

func (m *Entity) GetBoolValue() bool {
	if m != nil && m.BoolValue != nil {
		return *m.BoolValue
	}
	return false
}

func (m *Entity) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *Entity) GetStringList() []string {
	if m != nil {
		return m.StringList
	}
	return nil
}

func (m *Entity) GetInt64List() []int64 {
	if m != nil {
		return m.Int64List
	}
	return nil
}

type Request struct {
	ReqId            *string   `protobuf:"bytes,1,req,name=req_id" json:"req_id,omitempty"`
	Cmd              *string   `protobuf:"bytes,2,req,name=cmd" json:"cmd,omitempty"`
	Entity           []*Entity `protobuf:"bytes,3,rep,name=entity" json:"entity,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetReqId() string {
	if m != nil && m.ReqId != nil {
		return *m.ReqId
	}
	return ""
}

func (m *Request) GetCmd() string {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ""
}

func (m *Request) GetEntity() []*Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type Response struct {
	ReqId            *string   `protobuf:"bytes,1,req,name=req_id" json:"req_id,omitempty"`
	Result           *int32    `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	Errmsg           *string   `protobuf:"bytes,4,opt,name=errmsg" json:"errmsg,omitempty"`
	Entity           []*Entity `protobuf:"bytes,3,rep,name=entity" json:"entity,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetReqId() string {
	if m != nil && m.ReqId != nil {
		return *m.ReqId
	}
	return ""
}

func (m *Response) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *Response) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

func (m *Response) GetEntity() []*Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type Message struct {
	Request          *Request  `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Response         *Response `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Message) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
}
